### ISSUE TITLE
I tried to open the project in Unity but 9 errors popped out, should i install some stuff first?

### ISSUE THREAD

**Issue by johnZone99** [janilein/IndoorNavigation#4]
Hi jan, i followed your tutorial on https://blog.raccoons.be/arcore-powered-indoor-navigation-unity, Great Work! but i faced some difficulties opening the project, Could you help Please.
these are some of the errors :

An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.2d.sprite: Package [com.unity.2d.sprite@1.0.0] cannot be found
    com.unity.2d.tilemap: Package [com.unity.2d.tilemap@1.0.0] cannot be found
    com.unity.timeline: Package [com.unity.timeline@1.1.0] cannot be found

#######################

PrecompiledAssemblyException: Multiple precompiled assemblies with the same name nunit.framework.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 

#######################

Failed to load 'C:/Users/aymen/Downloads/Compressed/IndoorNavigation-master/IndoorNavigation-master/Assets/Scenes/TestScene/NavMesh-NavMesh 2.asset' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)
UnityEditor.SearchableEditorWindow:OnSearchForReferences()

**Comment by janilein** [comment]
I used Unity 2019.3.0a10 to develop the application. Maybe try opening it with that version?

**Comment by johnZone99** [comment]
@janilein Yes I was working on Unity 2018 really appreciate bro, I have small issues how can i contact you if you don't mind.
