### ISSUE TITLE
indoornavcontroller get executed fine but when I build the project I noticed the blue dot does not move!! 

### ISSUE THREAD

**Issue by johnZone99** [janilein/IndoorNavigation#5]
is there anything I should modify, I built the project, the blue dot rotates half circle and freeze, in fact, indoornavcontroller is tracking and executing fine what's the problem?! should the map be the same as yours!?

**Comment by janilein** [comment]
Probably a GameObject not dragged to the correct script. You do not need to use the same map, you can customise your own map as long as you respect to mapping of the real world distances to the Unity distances.

**Comment by aymzone** [comment]
Do you tried to download the project and build it, you don't need to have a QR scan I delete the imageRecognition and all associated scripts, I feel the project is lacking something, are you sure I don't need extra modifications? (I'm trying to optimize your code so you can share it without any errors and then people can benefit from it) @janilein

**Comment by johnZone99** [comment]
it does not work with Huawei p20 pro
