### ISSUE TITLE
do I need to scan the area for the tracking to work if not how it is working? and how to activate area learning to optimize tracking? 

### ISSUE THREAD

**Issue by johnZone99** [janilein/IndoorNavigation#6]

**Comment by janilein** [comment]
It is one of the “Can it be improved?” points mentioned in my blog (https://blog.raccoons.be/arcore-powered-indoor-navigation-unity). It has been a year, hopefully ARCore has an update by now that allows this. As mentioned in the blog also, for the project I developed a SLAM algortithm is used with a cold start.
